### ISSUE TITLE
mex won't run on macos-14 apple silicon

### ISSUE THREAD

**Issue by fangq** [matlab-actions/setup-matlab#100]
I tried to build mex files on macos-14 runner, and saw the below error

```
/Users/runner/hostedtoolcache/MATLAB/2022.1.999/arm64/MATLAB.app/bin/mex: line 358: /Users/runner/hostedtoolcache/MATLAB/2022.1.999/arm64/MATLAB.app/bin/maci64/mex: No such file or directory
```

full log is here

https://github.com/fangq/mcxcl/actions/runs/8258825592/job/22591739583

it appears that mex command was mislinked to the maci64 version, which does not exist.

**Comment by fangq** [comment]
never mind, it appears that I used an older version of matlab that does not support M1 processor, switching to R2023b solved the issue. here is the log

https://github.com/fangq/mcxcl/actions/runs/8268380829/job/22621104273

closing.

**Comment by mcafaro** [comment]
That's right. R2023b was the first native Apple Silicon version of MATLAB.
