### ISSUE TITLE
Barebones Ubuntu 22 image not able to run MATLAB command

### ISSUE THREAD

**Issue by NTmuir** [matlab-actions/setup-matlab#127]
I am currently experimenting with using a more bare-bones Ubuntu 22 image hosted via AWS EC2. I have installed Java and xfvb but I am experiencing an issue at runtime, so wondering if I am missing any other dependencies or if the Set Up MATLAB actions requires Java to be set on the Environment path beforehand?

As I can see the JDK is recognized in the Matlab session but unable to call the `libmwsimulink_slxsupport.so` that `myfunc` uses, which the Setup would have installed?
![image](https://github.com/user-attachments/assets/175125e4-7f02-4632-9648-d11aba4035ef)

### Image settings
Note this is using a barebones AMI Ubuntu image
![image](https://github.com/user-attachments/assets/d7ba3b3a-bebb-4216-857a-6e0a7f362e9b)

### YAML snippet (steps inc Managing Display and Java with bash)
```yaml
steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.3.0
        with:
          release: R2023b
          products: | # Use the "mpm" names of desired products
            Statistics_and_Machine_Learning_Toolbox
            DSP_System_Toolbox
            Signal_Processing_Toolbox
            Mixed-Signal_Blockset_Models
            MATLAB_Coder
            Simulink_Coder
            Embedded_Coder
            Requirements_Toolbox
            Simulink
            Simulink_Test
            Simulink_Check
            Simulink_Coverage
            Simulink_Design_Optimization
            Simulink_Design_Verifier
            Stateflow
            AUTOSAR_Blockset
            Sensor_Fusion_and_Tracking_Toolbox
            Model_Predictive_Control_Toolbox

      - name: Start Java & display server
        run: |
          sudo apt-get update 
          sudo apt-get install -y xvfb
          sudo apt-get install -y openjdk-11-jre
          sudo apt-get install -y openjdk-8-jre 
          matlab_jenv
          Xvfb :99 &
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Running Static Check Script 
        uses: matlab-actions/run-command@v2
        with:
          command: |
           je = jenv, myfunc;

```

Let me know if you require any other debug files or items

Thanks!

**Comment by mcafaro** [comment]
Hi @NTmuir,

The setup-matlab action does not require Java.

It looks like something about the libgbm1 package may be problematic on the system.

Can you show the log of setup-matlab? Can you also show the output of running `ldd /opt/actions-runner/_work/_tool/MATLAB/2023.2.999/x64/bin/glnxa64/builtins/simulink/slxsupport/mwlibmwsimulink_slxsupport_builtinimpl.so` as part of your workflow after setup-matlab (perhaps as part of your Start Java & display server step).

**Comment by NTmuir** [comment]
Hi @mcafaro, 

The setup of MATLAB doesn't look effected which is good:
![image](https://github.com/user-attachments/assets/8ca9d808-0bbb-48c2-b2e6-b1ccdfb8bccf)

Running the ldd comand for that static object file showed I was missing a few packages:
![image](https://github.com/user-attachments/assets/7a315538-a1c5-46fd-a525-d5d5e52b6e39)

I added these packages that were denoted as missing in order to satisfy the `mwlibmwsimulink_slxsupport_builtinimpl.so` 
```bash
sudo apt-get -y install libgbm-dev
sudo apt-get -y install libatk1.0-0
sudo apt-get -y install libatk-bridge2.0-0
sudo apt-get -y install libcups2-dev
sudo apt-get -y install libxdamage-dev
sudo apt-get -y install libxcomposite1
sudo apt-get -y install libxrandr-dev
sudo apt-get -y install libatspi2.0-dev
```
Now I am able to get to Simulink running, but it is still is registering these packages as missing:
![image](https://github.com/user-attachments/assets/698cb850-7535-4dfd-b9b1-8b1d2359deeb)

I can add these packages to my image but I just want to make sure the process I am following is correct for obtaining the required packages.

**Comment by NTmuir** [comment]
Perfect thank you @mcafaro for outlining where the more detailed documentation for this is!
