### ISSUE TITLE
matlab does not start correctly if the HOME environment variable is redefined

### ISSUE THREAD

**Issue by traversaro** [matlab-actions/setup-matlab#31]
I have a CI job in which I run from the command line the following command:
~~~
matlab -nosplash -nojvm -logfile "matlabVersionLog.cmaketmp" -nodesktop -nodisplay -batch "version, exit"
~~~

that correctly outputs:
~~~
	Sponsored License -- for use in support of a program or activity sponsored by MathWorks.
	Not for government, commercial or other non-sponsored organizational use.


ans =

    '9.11.0.1809720 (R2021b) Update 1'
~~~

As soon as I redefined the `HOME` environment variable, the execution fails with:
~~~
License checkout failed.
License Manager Error -1
The license.dat file cannot be found.

Troubleshoot this issue by visiting: 
https://www.mathworks.com/support/lme/R2021b/1

Diagnostic Information:
Feature: MATLAB 
License path: /home/runner/newhome/.matlab/R2021b_licenses:/usr/local/MATLAB/R2021b/licenses/license.dat:/usr/loca
l/MATLAB/R2021b/licenses 
Licensing error: -1,359. System Error: 2
~~~

An example of the problem can be found at https://github.com/traversaro/matlab-actions-no-home-mre/actions/runs/1973540132 (related code: https://github.com/traversaro/matlab-actions-no-home-mre/blob/main/.github/workflows/mre.yml#L23).

**Comment by traversaro** [comment]
To provide a bit more context to the problem: I am trying to run CMake test suite, including the tests that use MATLAB, in GitHub Actions, to avoid regression in the `FindMatlab` CMake module, see https://gitlab.kitware.com/cmake/cmake/-/issues/21912#note_1013804 and https://github.com/traversaro/cmake-nightly-testing-runner/issues/3 for more context. 

Apparently CMake while executing its tests is redefining the `HOME` environment variable to avoid polluting the real home directory with byproduct of its tests, and so due to that behaviour and the issue described in this issue, the tests are not passing.

**Comment by mcafaro** [comment]
Hi @traversaro,

This occurs because MATLAB is looking for its license file in $HOME/.matlab and by changing $HOME it can no longer find it. 

Two ideas:

1) Copy the $HOME/.matlab directory to the home used by CMake after executing setup-matlab. It is setup-matlab that sets up the $HOME/.matlab directory.

OR

2) Set the $HOME env var to the old home when calling MATLAB:

```
HOME=/home/runner/newhome matlab -nosplash -nojvm -logfile "matlabVersionLog.cmaketmp" -nodesktop -nodisplay -batch "version, exit"
```

Best,
Mark

**Comment by traversaro** [comment]
Thanks! From my point of view we can close the issue, as the problem is closed and I do not think we can change anything at this level.
