### ISSUE TITLE
R2022a support

### ISSUE THREAD

**Issue by xsro** [matlab-actions/setup-matlab#32]
Thanks to the team for the CI support ❤️ 
Since the `R2022a` has been released, is there any information to tell when will we be able to use this version in Github actions

**Comment by mcafaro** [comment]
Hi @xsro,

There is a week or two delay in us posting a new release to GitHub Actions. I will post here when `R2022a` is available. The `latest` release keyword will also switch over automatically.

Best,
Mark

**Comment by mcafaro** [comment]
R2022a is now available.
