### ISSUE TITLE
MATLAB R2022a: MEX does not support the Fortran compilers specified in the official documentation

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/setup-matlab#33]
Hello!

Thank you very much for providing MATLAB on GitHub Actions. It is great that MATLAB R2022a is now made available! 

According to [the official documentation](https://www.mathworks.com/support/requirements/supported-compilers.html), MATLAB R2022a supports `gfortan8.x` as the Fortran compiler for MEX on Linux. However, according to my [test on GitHub Actions](https://github.com/equipez/test_matlab/actions/runs/2002389041), `gfortran 8` fails to compile the official `timestwo.F`, [the error message](https://github.com/equipez/test_matlab/runs/5596035216?check_suite_focus=true) being
```
gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’;
  did you mean ‘-Wno-argument-mismatch’?
```

Nevertheless, `gfortran 10` and `11` succeed, even though they are not supported officially. 

I am not sure whether this comes from MATLAB R2022a itself, or from the setup of MATLAB on GitHub Actions. Thank you for having a look at it. 

**Update** (20220319): The problem has been reproduced using "MATLAB Online". The official configuration of MATLAB Online (R2022a with gfortran 8.3.0) fails to run the following command, the error message being the same as above.
```
mex('-setup', '-v', 'FORTRAN'); mex('-v', fullfile(matlabroot, 'extern', 'examples', 'refbook', 'timestwo.F')); 
```
Therefore, this seems not a problem of GitHub Actions, but a bug of MATLAB R2022a. 

Many thanks for everything!

Best regards,
Zaikun

**Comment by mcafaro** [comment]
Hi @zaikunzhang,

Can you try running your jobs again? R2022a was just posted.

Best,
Mark

**Comment by zaikunzhang** [comment]
Hello Mark @mcafaro ,

Thank you for your quick response!  

I triggered [my jobs again just now](https://github.com/equipez/test_matlab/actions/runs/2004520177), and the results were still the same: MATLAB R2022a on Ubuntu 20.04 works with `gfortran` 10 and 11, but not 8 (or 9), which does not comply with the [official documenation](https://www.mathworks.com/support/requirements/supported-compilers.html). 

I am not sure what will happen on a local machine since I do not have a machine with MATLAB R2022a installed.

BTW, I am probably one of the first users who get to know that you have posted MATLAB R2022a on GitHub Actions, because I have MATLAB actions that run several times every day ---  I woke up to find that they failed last night, and discovered that the failure was because MATLAB was updated and the default gfortran (gfortran 9, I think) of Ubuntu 20.04 on GitHub Actions did not work with MEX.

**Comment by zaikunzhang** [comment]
Update: Why does the error occur?

According to the documentation of [`gfortran 10.1.0`](https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gfortran/Option-Summary.html#Option-Summary) and [`gfortran 9.4.0`](https://gcc.gnu.org/onlinedocs/gcc-9.4.0/gfortran/Option-Summary.html#Option-Summary), the `-fallow-argument-mismatch` flag was first introduced to `gfortran` in 10.1.0. Therefore, there is no hope that `gfortran 8.x` could recognize it.

Below are the MEX configuration files of MATLAB Version 9.12.0.1896817 (R2022a, Operating System: Linux 4.14.215-0414215-generic). As we can see, gfortran6.xml specifies `-fallow-argument-mismatch` as a compilation option. That is why `gfortran 8.x` cannot work with it.

BTW, another question: What is the relation and difference between gfortran6.xml and gfortran.xml? Which one defines the compilation options when MEX is invoked? In my investigation, it seems that gfortran6.xml is playing the role, although the name of this file is a bit confusing --- I thought it was the configration for gfortran 6 or below.

1. gfortran6.xml located at fullfile(matlabroot,'bin', 'glnxa64', 'mexopts', 'gfortran6.xml'):
```
<?xml version="1.0" encoding="UTF-8" ?>
<config
    Name="gfortran"
    ShortName="gfortran"
    Manufacturer="GNU"
    Version="$GFORTRAN_VERSION"
    Language="FORTRAN"
    Priority="A"
    Location="$GFORTRAN_INSTALLDIR" >
    <Details
        CompilerExecutable="$FC"
        CompilerDefines="$DEFINES"
        CompilerFlags="$FFLAGS"
        OptimizationFlags="$FOPTIMFLAGS"
        DebugFlags="$FDEBUGFLAGS"
        IncludeFlags="$INCLUDE"
        LinkerLibraries="$LINKLIBS"
        LinkerOptimizationFlags="$LDOPTIMFLAGS"
        LinkerDebugFlags="$LDDEBUGFLAGS"

        CompilerDefineFormatter="-D%s"
        LinkerLibrarySwitchFormatter="-l%s"
        LinkerPathFormatter="-L%s"
    />
    <vars
        CMDLINE1="$FC -c $DEFINES $INCLUDE $FFLAGS $OPTIM $SRC -o $OBJ"
        CMDLINE2="$LDF $LDFLAGS $LDTYPE $LINKOPTIM $LINKEXPORTVER $OBJS $FLIBS $LINKLIBS -o $EXE"

        FC="$GFORTRAN_INSTALLDIR/gfortran"
        DEFINES=""
        FFLAGS="-fexceptions -fbackslash -fPIC -fno-omit-frame-pointer -fallow-argument-mismatch"
        INCLUDE="-I&quot;$MATLABROOT/extern/include&quot; -I&quot;$MATLABROOT/simulink/include&quot;"
        FOPTIMFLAGS="-O2"
        FDEBUGFLAGS="-g"

        LDF="$FC"
        LDFLAGS="-pthread"
        LDTYPE="-shared"
        LINKEXPORT="-Wl,--version-script,$MATLABROOT/extern/lib/$ARCH/fexport.map"
        LINKEXPORTVER="-Wl,--version-script,$MATLABROOT/extern/lib/$ARCH/fortran_exportsmexfileversion.map"
        MWCPPLIB="&quot;$MATLABROOT/sys/os/$ARCH/orig/libstdc++.so.6&quot;"
        LINKLIBS="-Wl,-rpath-link,$MATLABROOT/bin/$ARCH  -L&quot;$MATLABROOT/sys/os/$ARCH/orig&quot; -L&quot;$MATLABROOT/bin/$ARCH&quot; $MWCPPLIB -lmx -lmex -lmat -lm -L&quot;$GFORTRAN_LIBDIR&quot; -lgfortran"
        LDOPTIMFLAGS="-O"
        LDDEBUGFLAGS="-g"
        MW_GLIBC_SHIM="$MW_GLIBC_SHIM"

        OBJEXT=".o"
        LDEXT=".mexa64"

        SETENV="FC=&quot;$FC&quot;
                FFLAGS=&quot;$FFLAGS $DEFINES&quot;
                FOPTIMFLAGS=&quot;$FOPTIMFLAGS&quot;
                FDEBUGFLAGS=&quot;$FDEBUGFLAGS&quot;
                LD=&quot;$FC&quot;
                LDFLAGS=&quot;$LDFLAGS $LDTYPE $LINKLIBS $LINKEXPORT&quot;
                LDDEBUGFLAGS=&quot;$LDDEBUGFLAGS&quot;">

        </vars>

    <!---Wl,-twolevel_namespace -undefined error $LDFEXPORT-->
    <client>
        <engine
            LINKLIBS="$LINKLIBS $MW_GLIBC_SHIM -leng"
            LINKEXPORT=""
            LINKEXPORTVER=""
            LDEXT=""
            LDTYPE=""
        />
    </client>
    <locationFinder>
        <GFORTRAN_INSTALLDIR>
            <and>
                <or>
                    <cmdReturns name="which gfortran" />
                    <fileExists name="/usr/local/bin/gfortran" />
                </or>
                <dirExists name="$$"/>
            </and>
        </GFORTRAN_INSTALLDIR>
        <GFORTRAN_LIBDIR>
            <and>
                <or>
                    <cmdReturns name="which gfortran" />
                    <fileExists name="/usr/local/bin/gfortran" />
                </or>
                <cmdReturns name="gfortran -print-file-name=libgfortran.so" />
                <dirExists name="$$" />
            </and>
        </GFORTRAN_LIBDIR>
        <GFORTRAN_VERSION>
            <and>
                <or>
                    <cmdReturns name="which gfortran" />
                    <fileExists name="/usr/local/bin/gfortran" />
                </or>
                <cmdReturns name="gfortran -dumpversion | awk -F '.' '$1>=6' " />
            </and>
        </GFORTRAN_VERSION>
    </locationFinder>
</config>
```

2. gfortran.xml located at fullfile(matlabroot,'bin', 'glnxa64', 'mexopts', 'gfortran.xml'):
```
<?xml version="1.0" encoding="UTF-8" ?>
<config
    Name="gfortran6-"
    ShortName="gfortran6-"
    Manufacturer="GNU"
    Version="$GFORTRAN_VERSION"
    Language="FORTRAN"
    Priority="B"
    Location="$GFORTRAN_INSTALLDIR" >
    <Details
        CompilerExecutable="$FC"
        CompilerDefines="$DEFINES"
        CompilerFlags="$FFLAGS"
        OptimizationFlags="$FOPTIMFLAGS"
        DebugFlags="$FDEBUGFLAGS"
        IncludeFlags="$INCLUDE"
        LinkerLibraries="$LINKLIBS"
        LinkerOptimizationFlags="$LDOPTIMFLAGS"
        LinkerDebugFlags="$LDDEBUGFLAGS"

        CompilerDefineFormatter="-D%s"
        LinkerLibrarySwitchFormatter="-l%s"
        LinkerPathFormatter="-L%s"
    />
    <vars
        CMDLINE1="$FC -c $DEFINES $INCLUDE $FFLAGS $OPTIM $SRC -o $OBJ"
        CMDLINE2="$LDF $LDFLAGS $LDTYPE $LINKOPTIM $LINKEXPORTVER $OBJS $FLIBS $LINKLIBS -o $EXE"

        FC="$GFORTRAN_INSTALLDIR/gfortran"
        DEFINES=""
        FFLAGS="-fexceptions -fbackslash -fPIC -fno-omit-frame-pointer"
        INCLUDE="-I&quot;$MATLABROOT/extern/include&quot; -I&quot;$MATLABROOT/simulink/include&quot;"
        FOPTIMFLAGS="-O2"
        FDEBUGFLAGS="-g"
```

**Comment by mcafaro** [comment]
Hi @zaikunzhang,

As you noted, this does not appear to be an issue with the MATLAB actions for GitHub but instead with the underlying MEX command. I have asked the MEX team about it and will post again when I have more information.

Best,
Mark

**Comment by zaikunzhang** [comment]
Hello Mark @mcafaro ,

Thank you very much for forwarding the issue to the MEX team.

Indeed, I have submitted a bug report (Case number 05433449), but the MathWorks colleague who handled it seemed indifferent about it. I hope your forwarding will get some attention from the MEX team. I look forward to any updates. 

Many thanks for everything!

Best regards,
Zaikun

**Comment by ssankarmw** [comment]
@zaikunzhang ,
My apologies for not able to respond to this thread. This is bug with R2022a and we are fix it as soon as possible. These are the steps for a workaround for this bug. I am working on getting this fix in for R2022a but, it might take sometime. Meanwhile you are use this workaround in your scripts.
Please let me know if you run into any issues.  
0. clean up the prefdir 
`>> delete(fullfile(prefdir,'mex_FORTRAN_glnxa64.xml'))`
2. setup MEX compiler for Fortran
`>> mex -setup FORTRAN`
3. copy the MEX options file to the current directory 
`>> copyfile(fullfile(prefdir,'mex_FORTRAN_glnxa64.xml'), pwd)`

4. Add the following to the `<locationFinder> </locationFinder>` section of the XML file mex_FORTRAN_glnxa64.xml      
```
        <GFORTRAN_EXECUTABLE >
                <or>
                    <cmdReturns name="which gfortran" />
                    <fileExists name="/usr/local/bin/gfortran" />
                </or>
        </GFORTRAN_EXECUTABLE>
```
5. Replace 
`FC = $GFORTRAN_INSTALLDIR/gfortran`
with 
`FC = $GFORTRAN_EXECUTABLE`

With this change, you should be able to build MEX file
```
>> mex timestwo.F -v
…
…
>> MEX completed successfully.
```

This will fix all the MEX operations from this particular directory. For a persistent change, copy this file to the prefdir. 
`>> copyfile('mex_FORTRAN_glnxa64.xml', prefdir, 'f')`
Note : Any command to setup the fortran compiler will over-write this file.

**Comment by zaikunzhang** [comment]
Hello @ssankarmw !

Thank you very much for the detailed information. 

I feel relaxed that the problem is confirmed as a bug rather than my delusion.

The MathWorks colleague who handled my bug report  (Case number 05433449) was indifferent. He turned a deaf ear to me when he found I was using a trial license of MATLAB online. I explained to him in vain that I was not requesting any tech support,  --- the problem does not affect my projects, but trying to uncover a problem in the hope of fixing it. I am not even sure whether he passed the report to the MEX team or not. 

My post on [MATLAB Answers](https://www.mathworks.com/matlabcentral/answers/1674509-bug-in-matlab-r2022a-mex-does-not-support-gfortran-8-x-as-specified-in-the-official-documentation) got no luck to receive any attention either, although I am sure that there are MathWork staff overlooking the forum. 

Thank you very much again. My best wishes for fixing the bug. 

Best regards,
Zaikun
