### ISSUE TITLE
Setup with display for GUI testing?

### ISSUE THREAD

**Issue by peterson-tim-j** [matlab-actions/setup-matlab#51]
Hi, great work building these packages! Thanks. 

I'm trying to use it to run GitHub hosted Actions testing of my package [HydroSight](https://github.com/peterson-tim-j/HydroSight).  However, the tests are failing because my package uses graphical features and setup-matlab appears to start matlab with '-nodisplay'.  

Given that my package is heavily dependent upon a range of graphical features, is there any way to change matlab-actions/setup-matlab to enable the graphical environment?

FYI, if relevant my .yml testing file is [here](https://github.com/peterson-tim-j/HydroSight/blob/master/.github/workflows/testHydroSight.yml).

**Comment by mcafaro** [comment]
Hi Tim,

GitHub-hosted runners currently require '-nodisplay'. We would like to remove this restriction in the future but at the moment you need to use a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) to test features that require access to a display.

Best,
Mark

**Comment by peterson-tim-j** [comment]
Hi Mark,

Thanks for the reply. Good to hear to that removing the -nodisplay restriction is on your radar. 

Re solutions, unfortunately I'm very unlikely to be able to run a self-hosted runner for my public repo because of the security risks to my university. I see [here](https://au.mathworks.com/help/matlab/matlab_prog/continuous-integration-with-matlab-on-ci-platforms.html) that there are other CI systems that support Matlab.  Do you happen to know if any support testing of graphical outputs?

Thanks, Tim

**Comment by acampbel** [comment]
@peterson-tim-j  we plan to build this into the actions, but in the meantime take a look at [this repository](https://github.com/acampbel/AppTestingDemo) to see how you can setup a virtual display. Note you can set up a virtual display like this for any release, but there were specific changes in R2023b to enable the MATLAB actions to be able to leverage it so that release is needed.

**Comment by mcafaro** [comment]
GUI testing is supported in more recent versions of the actions (-nodisplay is no longer required), so I am going to close this issue as complete. As @acampbel mentioned, you still need to set up a virtual display because GitHub-hosted Linux runners do not have a display by default.
