### ISSUE TITLE
Error using BatchToken/consumeTokenData

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/setup-matlab#53]
MATLAB actions exit with 
```
Error using BatchToken/consumeTokenData
  Current time (03-Jan-2023 14:04:49) for token from license 40847642 is NOT in
  the time range for this token (02-Jan-2022 09:17:07 to 03-Jan-2023 09:17:07)
  
  Error in BatchToken.enableTokenLicenses
```
See, for example,

https://github.com/zequipe/test_matlab/actions/runs/3830109751/jobs/6517573208

Thank you for taking a look.

**Comment by mcafaro** [comment]
@zaikunzhang Thanks for reporting this issue. We are working on it.

**Comment by mcafaro** [comment]
This issue should be resolved. Please feel free to reopen if you continue to experience it.

**Comment by zaikunzhang** [comment]
Thank you @mcafaro . It works.
