### ISSUE TITLE
When will MATLAB R2023a be supported?

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/setup-matlab#61]
Hello! MATLAB R2023a is now released. When will it be available on GitHub Actions? Thank you.

**Comment by mcafaro** [comment]
Hi @zaikunzhang,

There is a week or two delay in us posting a new release to GitHub Actions. I will post here when R2023a is available. The latest release keyword will also switch over automatically.

Best,
Mark

**Comment by zaikunzhang** [comment]
> Hi @zaikunzhang,
> 
> 
> 
> There is a week or two delay in us posting a new release to GitHub Actions. I will post here when R2023a is available. The latest release keyword will also switch over automatically.
> 
> 
> 
> Best,
> 
> Mark

Hi @mcafaro , that sounds great! Thank you.

**Comment by zaikunzhang** [comment]
Great! I noted it today and have started using it, which works nicely. Thank you @mcafaro and your team!
