### ISSUE TITLE
When will MATLAB R2023b be available?

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/setup-matlab#71]
[R2023b has been released](https://www.mathworks.com/products/new_products/latest_features.html). When will it be available on GitHub Actions? Thanks.

**Comment by mcafaro** [comment]
Hi Zaikun,

There is a week or two delay in us posting a new release to GitHub Actions. I will post here when `R2023b` is available. The `latest` release keyword will also switch over automatically.

Best,
Mark

**Comment by zaikunzhang** [comment]
Starting a few hours ago (20230916),  `matlab-actions/setup-matlab@v2-beta` fails for `latest`, giving the following error information:
```
Dependencies are not available for MATLAB 'r2023b' on 'Ubuntu:jammy'. Use 'R2020a' or a later release on a supported Ubuntu distribution.
```
Thanks for taking a look.

**Comment by mcafaro** [comment]
R2023b is now available.

Note: If you are using `v2-beta` there is an issue with installing R2023b on Windows and Mac (Linux is OK). It may take until mid- to late-October to resolve. Please use `v1` or R2023a until that time.

**Comment by zaikunzhang** [comment]
Great! Thank you @mcafaro .

**Comment by gllmflndn** [comment]
Thanks @mcafaro for R2023b, it works fine! Would it be possible to mention and update on the [`README.md`](https://github.com/matlab-actions/setup-matlab/blob/main/README.md) when a new release is available?
