### ISSUE TITLE
MATLAB won't start on R2020b and R2021a Windows runners (v2-beta)

### ISSUE THREAD

**Issue by H0R5E** [matlab-actions/setup-matlab#76]
Hi, we were having some trouble with testing Windows runners for R2020b and R2021a with the `v2-beta` version of `setup-matlab`. For some reason, they won't start up properly when using the `run-command` action. The step just hangs until timeout.

I created a repository to demonstrate the issue. You can see the workflow [here](https://github.com/H0R5E/setup-matlab-windows-runner-issue/blob/main/.github/workflows/hello_world.yml) and the failed runs [here](https://github.com/H0R5E/setup-matlab-windows-runner-issue/actions/runs/6852704867).

Any help greatly appreciated, as always!

**Comment by mcafaro** [comment]
Thanks for the report @H0R5E. We are looking into it.

**Comment by H0R5E** [comment]
@mcafaro, I'm just checking to see if there is any update on this one?

Many thanks,

Mat

**Comment by H0R5E** [comment]
Just to note, I seem to be having some similar issues with R2023b, but this is more intermittent than with the versions reported in this issue. 

See [this run](https://github.com/H0R5E/WEC-Sim_Applications/actions/runs/7247225459/job/19740743221#step:10:8) for example.

**Comment by H0R5E** [comment]
Never mind! Seems [to be fixed!](https://github.com/H0R5E/setup-matlab-windows-runner-issue/actions/runs/7249527857)

Thanks for your help,

Mat

**Comment by acampbel** [comment]
Note, that at least for 20b, there is an issue on windows where it does not produce any log output. You can see for example that your hello world output never got to the GitHub log even though it ran successfully.

This is unfortunate, but not likely to change as it requires large changes to 20b to make that a reality. 

In the context of CI, this may look like a stall if you are running a long MATLAB session doing "real" work. For 21a though I would not expect this problem. Let us know if this happens in the future.
