### ISSUE TITLE
When will `v2-beta` become `v2`?

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/setup-matlab#79]
Hi, excuse me if this question is inappropriate. I have been using `v2-beta` [since March 22, 2023](https://github.com/matlab-actions/setup-matlab/issues/62#issuecomment-1479522143) after @mcafaro directed me to it. I have been wondering since then, when will it become `v2`? Thank you.

**Comment by davidbuzinski** [comment]
Hi @zaikunzhang,

Thanks for reaching out! We are scheduling to release a stable `v2` around the beginning of February this year (a few weeks from now). I will respond on this ticket when it's officially released.

Best,
David

**Comment by zaikunzhang** [comment]
> Hi @zaikunzhang,
> 
> 
> 
> Thanks for reaching out! We are scheduling to release a stable `v2` around the beginning of February this year (a few weeks from now). I will respond on this issue when it's officially released to keep you updated.
> 
> 
> 
> Best,
> 
> David

Great! Thank you.

**Comment by davidbuzinski** [comment]
Hi @zaikunzhang 

We have officially release v2.0.0. Feel free to migrate `setup-matlab@v2`, `run-command@v2`, `run-test@v2`, and `run-build@v2`,

**Comment by zaikunzhang** [comment]
This is fantastic! Thank you!
