### ISSUE TITLE
Document the use of 'latest' as release parameter - v2-beta

### ISSUE THREAD

**Issue by pauldruce** [matlab-actions/setup-matlab#85]
I noticed that in the action definition: https://github.com/matlab-actions/setup-matlab/blob/v2-beta/action.yml
the default value for the 'release' input is 'latest'. However, this is not documented anywhere in the README. 

The desired use case is to run a workflow using an older version of MATLAB such as R2020b, and the latest available MATLAB. 
Currently, using the documentation https://github.com/matlab-actions/setup-matlab/tree/v2-beta#set-up-matlab doesn't mention you can pass in the string 'latest' to get the latest. 

I should mention this is in the v2-beta for the setup-matlab action.

**Comment by mcafaro** [comment]
Good point. We will update the documentation to make this more clear.

**Comment by VisLab** [comment]
I'm not sure whether this update will fix my problem, but GitHub is no longer supporting node16 and so the command and test actions are failing.

**Comment by mcafaro** [comment]
@VisLab We are working on the transition to Node 20. I would not expect the GitHub Actions to fail with Node 16. Can you point to a job experiencing the issue?

**Comment by VisLab** [comment]
I've tried a number of unsuccessful variations and maybe I am failing to
run correctly.

For example in:
https://github.com/hed-standard/hed-matlab/actions/runs/7701527204/job/20987764939
which is my latest try, I tried the run-command option. The Yaml file is:

https://github.com/hed-standard/hed-matlab/blob/main/.github/workflows/ci.yaml

The runAllTests in the tests directory successfully runs all tests
locally.  Thx!

**Comment by mcafaro** [comment]
@VisLab It looks like the command is missing a closing parenthesis after the `addpath(genpath("tests")`.

The command is currently:
`addpath(genpath("hedcode")), addpath(genpath("tests"), runAllTests`

But should be:
`addpath(genpath("hedcode")), addpath(genpath("tests")), runAllTests`

Can you try adding the closing parenthesis and see if that resolves the issue.

**Comment by mcafaro** [comment]
https://github.com/marketplace/actions/setup-matlab now documents and shows an example of `release: latest`
