### ISSUE TITLE
`setup-matlab@v2`: issues with Parallel Computing Toolbox

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/setup-matlab#94]
Hi @mcafaro ,

How does the built-in `cache` of `setup-matlab@v2` distinguish different caches? Does it respect the `with`, especially `release` and `products`? As far as I have observed, it does not respect `products`. This seems to be a bug. 

Thank you for taking a look. 

Best regards,
Zaikun

**Comment by mcafaro** [comment]
It caches MATLAB by platform, architecture, release and products. Yes, it should respect the `release` and `products` provided in `with`. If you add or remove a product from the `products` list, we have to recreate the cache from scratch.

Please also remember that the GitHub cache is limited to [10 GB and 7 days](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy).

**Comment by zaikunzhang** [comment]
OK. My observation was wrong. Now I see the real problem: in previous versions, `setup-matlab` installs "Parallel Computing Toolbox" by default (I cannot find the documentation anymore, but I remember reading it somewhere). But this is not the case in the latest version. Am I right?

**Comment by mcafaro** [comment]
That is right. `v2-beta` required Parallel Computing Toolbox, so it would install it by default. `v2` no longer has that requirement. `v2` only installs MATLAB by default.

**Comment by zaikunzhang** [comment]
I added "Parallel_Computing_Toolbox" to the products. It was installed, but did not work. See 

See https://github.com/zequipe/prima/actions/runs/7880910734/job/21503678625

**Comment by zaikunzhang** [comment]
> I added "Parallel_Computing_Toolbox" to the products. It was installed, but did not work.
> 
> See https://github.com/zequipe/prima/actions/runs/7880910734/job/21503678625

I find that all `parfor` receive the following message: 
```
2024-02-13T03:14:27.9851980Z Starting parallel pool (parpool) using the 'Processes' profile ...
2024-02-13T03:14:41.0675949Z Parallel pool using the 'Processes' profile is shutting down.
```
Nothing happens between these two lines. Is this expected or a bug?

**Comment by mcafaro** [comment]
There is a known issue with `parpool` at the moment. We are working on it.

**Comment by davidbuzinski** [comment]
Hi @zaikunzhang ,

The issues with Parallel Computing Toolbox should now be resolved. Please let us know if you continue to see them.

Thanks,
David

**Comment by zaikunzhang** [comment]
> Hi @zaikunzhang ,
> 
> 
> 
> The issues with Parallel Computing Toolbox should now be resolved. Please let us know if you continue to see them.
> 
> 
> 
> Thanks,
> 
> David

Thank you, @davidbuzinski . It is working now.
