### ISSUE TITLE
`setup-matlab@v2` with `cache: true`: Post setup fails randomly (not very often) 

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/setup-matlab#98]
Hi,

Post setup sometimes fails, although very rarely. 

See the workflow run at https://github.com/zequipe/prima/actions/runs/7940609085/job/21682087157. 

The failure happens randomly. I have observed this two or three times. Thank you for taking a look.

Best regards,
Zaikun

**Comment by mcafaro** [comment]
This looks like an issue with GitHub Actions cache service. I see some other projects running into similar errors. It may be a temporary outage. If it continues, we can look into treating issues communicating with GitHub Actions cache service as a warning rather than an error.
